# Generated by Django 3.2.9 on 2021-12-02 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_auto_20211202_2330'),
        ('message_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recieved',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received', to='user_accounts.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='user_accounts.user'),
        ),
    ]
