# Generated by Django 3.2.9 on 2021-12-03 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('message_content', '0002_auto_20211202_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recieved',
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='chat.chat'),
        ),
    ]
