# Generated by Django 3.2.9 on 2021-12-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_content', '0003_auto_20211203_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
    ]
