# Generated by Django 3.2.9 on 2021-12-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_content', '0005_alter_message_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.CharField(max_length=300),
        ),
    ]
