# Generated by Django 3.2.9 on 2021-12-03 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message_content', '0002_auto_20211202_2341'),
        ('user_accounts', '0003_auto_20211202_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received', to='message_content.message')),
                ('recieved', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received', to='user_accounts.user')),
            ],
        ),
    ]
