# Generated by Django 3.2.9 on 2021-12-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_content', '0004_remove_message_chat'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='message',
        ),
        migrations.AddField(
            model_name='chat',
            name='message',
            field=models.ManyToManyField(to='message_content.Message'),
        ),
    ]
