# Generated by Django 3.2.9 on 2021-12-03 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_auto_20211202_2330'),
        ('chat', '0002_auto_20211203_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='user_accounts.user'),
        ),
    ]
