# Generated by Django 3.2.9 on 2021-12-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='recieved',
            new_name='received',
        ),
    ]
