# Generated by Django 3.2.9 on 2021-12-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_user_chats'),
        ('chat', '0004_rename_recieved_chat_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='received',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sent',
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(to='user_accounts.User'),
        ),
    ]
