# Generated by Django 3.2.9 on 2021-12-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_user_chats'),
        ('chat', '0005_auto_20211203_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(max_length=2, to='user_accounts.User'),
        ),
    ]
