# Generated by Django 3.2.9 on 2021-12-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_user_chats'),
        ('message_content', '0004_remove_message_chat'),
        ('chat', '0006_alter_chat_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.ManyToManyField(blank=True, to='message_content.Message'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(blank=True, to='user_accounts.User'),
        ),
    ]
