# Generated by Django 3.2.9 on 2021-12-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_sent'),
        ('user_accounts', '0003_auto_20211202_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(blank=True, to='chat.Chat'),
        ),
    ]
