# Generated by Django 3.2.9 on 2021-12-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_content', '0005_alter_message_owner'),
        ('user_accounts', '0004_user_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='messages',
            field=models.ManyToManyField(blank=True, to='message_content.Message'),
        ),
    ]
